plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "F:\\bestStudentClone\\signaturePg\\signatur\\build"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]